### ISSUE TITLE
Issue inserting Timestamp into Synapse

### ISSUE THREAD

**Issue by chopraarjun** [microsoft/sql-spark-connector#130]
Scala: 2.12
Spark: Databricks 7.6 ( spark 3.0)

While inserting with append mode into synapse table with datatype as datetime2 getting error Invalid columnType for bcp coldid 17

df.selectExpr("*", "currentTimestamp() as timestamp)
.write
.format
...
.save

Additional waring seen for all the columns.... as differing column datatype for spark dataframe and spark column where as both of them have same dataype and name . this waning seen even for int. but on converting timetsmap to string it gets inserted into column with varchar type.

**Comment by arvindshmicrosoft** [comment]
Dear @chopraarjun - there is a specific connector to connect to Azure Synapse Analytics Dedicated SQL Pool (a.k.a. "SQL DW") from within Azure Databricks: https://docs.microsoft.com/en-us/azure/databricks/data/data-sources/azure/synapse-analytics

Please use that method, because this connector has not been designed for use with Azure Synapse Analytics Dedicated SQL Pools / SQL DW. If you see the same issue with Azure SQL DB or SQL Server as a target, please reply to this with a few more details, such as the destination table schema, for us to investigate.

**Comment by luxu1-ms** [comment]
issue solved.
