### ISSUE TITLE
An error occurred while calling o144.save. error while calling spill() on org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter@54da06eb : No space left on device

### ISSUE THREAD

**Issue by girimedi** [microsoft/sql-spark-connector#208]
Hello,
I m doing a sparksql join on 5 data frame and trying to write the resulting dataframe to a table and getting the following error. 
An error occurred while calling o144.save. error while calling spill() on org.apache.spark.util.collection.unsafe.sort.UnsafeExternalSorter@54da06eb : No space left on device

I looked at the driver logs and it looks like it is issuing a collect call before write and causing memory issues:
INFO DAGScheduler: Got job 5 (collect at ReliableSingleInstanceStrategy.scala:94) with 248 output partitions

Im using jdbc driver mssql-jdbc-8.1.1 and park-mssql-connector_2.12:1.2.0

**Comment by moredatapls** [comment]
Hi, the `.collect()` call you mentioned only returns one `Iterator[Int](1)` per partition that is written. On a functioning system this should not cause any exceptions.

The error "No space left on device" happens if your disk is full or if you're facing other storage-related issues. Most likely the error is caused by some issue with your disk or some wrong configuration on your side. If you google the "No space left on device" error there are many guides that you can follow to debug it on Linux, did you try those already?

**Comment by girimedi** [comment]
I have tried a few things and they din't help. If i run the same query and save to parquet files and then read the parquet files with another spark job and then write to sql server I m not facing any issues. The issue shows up when i try to write results of the query directly to database.

**Comment by girimedi** [comment]
you were right, did more research on this. Not the driver issue. For anyone looking in the future, i m working on aws glue,  if you are on spark create your spark session like this:

spark = glueContext.spark_session.builder.config("spark.sql.broadcastTimeout", "36000").config("spark.sql.adaptive.enabled",True).config("spark.sql.adaptive.skewJoin.enabled",True).
