### ISSUE TITLE
Default mode of Savemode overwrite should be Truncate and not drop/recreate.

### ISSUE THREAD

**Issue by denzilribeiro** [microsoft/sql-spark-connector#23]
Today JDBC defaults when you use savemode overwrite is to truncate -  http://spark.apache.org/docs/latest/sql-data-sources-jdbc.html   --> “It defaults to false"

This has a few problems but the main one is that we don't maintain schema.
a. A table with columnstore now becomes a heap/rowstore
b. Any other secondary indexes are lost

We should make the default when you have savemode overwrite to Truncate and not drop/recreate.

**Comment by shivsood** [comment]
Spark JDBC default for isTruncate is False in overwrite scenario.

https://spark.apache.org/docs/latest/sql-data-sources-jdbc.html

This is a JDBC writer related option. When SaveMode.Overwrite is enabled, this option causes Spark to truncate an existing table instead of dropping and recreating it. This can be more efficient, and prevents the table metadata (e.g., indices) from being removed. However, it will not work in some cases, such as when the new data has a different schema. It defaults to false. This option applies only to writing.

From JDBCOptions.scala
// ------------------------------------------------------------
  // Optional parameters only for writing
  // ------------------------------------------------------------
  // if to truncate the table from the JDBC database
  val isTruncate = parameters.getOrElse(JDBC_TRUNCATE, "false").toBoolean

**Comment by shivsood** [comment]
Changing JDBC default is a spark interface discussion. Connector uses the JDBC interface and should use the JDBC defaults.  Closing this here, please open a Spark JIRA if still required.
