### ISSUE TITLE
Check for embedded quotes to avoid SQLi attacks

### ISSUE THREAD

**Issue by arvindshmicrosoft** [microsoft/sql-spark-connector#82]
Some places in the code [sample](https://github.com/microsoft/sql-spark-connector/blob/931c5e3d9cd5ca5a5562c74777118c99abca3034/src/main/scala/com/microsoft/sqlserver/jdbc/spark/utils/BulkCopyUtils.scala#L192) execute SQL without checking for potentially dangerous embedded chars, leaving the door open for SQLi attacks (granted, there is restricted negative impact given the user is directly executing the code under their own creds). Ideally the code should check for these chars and escape them out.

**Comment by luxu1-ms** [comment]
My initial thought is to use brackets for table name, but then concerned that below example will still inject sql db. So I tried prepared statement in PR #138, but it turns out table name cannot be parameter in prepared statement.
sql statement in src code: 
``
SELECT * FROM ${table} WHERE 1=0; ($table is user input)
``
possible sql injection examples;
``
SELECT * FROM [table_a]; DROP table table_b --] WHERE 1=0;
''

**Comment by luxu1-ms** [comment]
I can inject sql table set dbtable = "test00(Col1 nvarchar(4)); DROP TABLE test1--", then my test1 will be dropped and test00 will be created. (inject the sql string in mssqlCreateTable()).

For now I do not think SQL Injection is a vulnerability in spark mssql connector.
1. The main point is that user who is creating / dropping / editing a sql table by JDBC must have the credentials already and could just open their own connection. 
2. IMO spark has sql strings which might be vulnerable to sql injection. I think it is better to fix it in spark end.
